# TensorFlow Concepts

In [1]:
# Import TensorFlow
import tensorflow as tf

print(tf.__version__)

2.12.0


In [2]:
# Create tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of Dimensions of a tensor (ndim stands for number of dimensions)

scalar.ndim

0

In [5]:
# Create a vector

vector = tf.constant([10,10])
vector

1

In [6]:
# Check the dimensions of vector

vector.ndim

1

In [8]:
# Create a Matrix

matrix = tf.constant([[10,7], [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [9]:
# Dimensions of a matrix
matrix.ndim

2

In [12]:
# Create a matrix with specified constant

specified_matrix = tf.constant([[10.,7],[7.,10], [3.0,13]], dtype = tf.float16, )
print(specified_matrix)
print(specified_matrix.ndim)

tf.Tensor(
[[10.  7.]
 [ 7. 10.]
 [ 3. 13.]], shape=(3, 2), dtype=float16)
2


In [14]:
# Create a Tensor, 3 dimensions

tensor = tf.constant([[[10,7],[7.,10]], [[3,13.],[13.,3]], [[14,4],[4,19]]])
tensor

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[10.,  7.],
        [ 7., 10.]],

       [[ 3., 13.],
        [13.,  3.]],

       [[14.,  4.],
        [ 4., 19.]]], dtype=float32)>

In [15]:
# Dimensions of tensor

tensor.ndim

3

What we've created so far:

* Scalar: A single number
* Vector: A number with a direction
* Matrix: A 2-dimensions array of numbers
* Tensor: an n-dimensions array of numbers (Where n is any number)

### Creating tensors with `tf.Variable`

In [17]:
# Create the same tensor with tf.Variable() as above

changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [19]:
# Change element in changeable tensor

changeable_tensor[0] = 7

TypeError: 'ResourceVariable' object does not support item assignment

In [21]:
# Using .assign()

changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [ ]:
# Trying to change value in unchangeable_tensor

unchangeable_tensor[0].assign(7)

### Creating Random Tensors 

* Random tensors are tensors of some arbitrary size which contain random numbers
* Model is initilized with random weights. Begins to update weights based on input data. 

In [39]:
# Create two random but the same tensor

random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42) # seed 2
random_2 = random_2.normal(shape = (3,2))

random_1,random_2, random_1 == random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor
* (valuable for when you want to shuffle your data so that the inherent order doesnt affect learning)
* The pattern that the NN learns may be biased if the data is ordered
* Rule 4: If both gloval and operation seeds are set, both seeds are used in conjunction. 
    * If only local seet is used, output wont be deterministic, reproduceable randomness

In [76]:
# Shuffle a tensor 

not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])

# Shuffle our non_shuffled tensor
tf.random.set_seed(13) # Global Seed
tf.random.shuffle(not_shuffled, seed = 20) #Operation level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]])>

### Other ways to make tensors

In [83]:
# Create a tensor of all ones
tf.ones(shape = [3,3])


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [87]:
# Create a tensor of all zeroes
tf.zeros([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors

The main different between NumpY arrays and TensorFlow tensors is that tensors can be run on a GPU computing. 

In [90]:
# Turning NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32) # Create a NumPy array between 1 and 25

numpy_A


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [105]:
# Converting a NumPy Array to a tensor
A = tf.constant(numpy_A, shape = (6,4)) #Converting to tensor
B = tf.constant(numpy_A, shape = (3,4,2)) # Converting to a vector
A, B

(<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])>,
 <tf.Tensor: shape=(3, 4, 2), dtype=int32, numpy=
 array([[[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8]],
 
        [[ 9, 10],
         [11, 12],
         [13, 14],
         [15, 16]],
 
        [[17, 18],
         [19, 20],
         [21, 22],
         [23, 24]]])>)

### Getting information about tensors
* Shape: Length of each dimension of a tensor | tensor.shape
* Rank: The number of tensor dimensions. A scalar has rank 0. Matrix = rank 2. | tensor.ndim
* Axis or Dim: A particular dimensions of a tensor | tensor[0], tensor[:, 1]
* Size: Total # of items in the tensor | tf.size(tensor)

In [107]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape = [2,3,4,5]) # 2 sets each with 3 matrices with 4 rows each with 5 elements
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [108]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [112]:
# Get various attributes of a tensor

print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions (rank): ", rank_4_tensor.ndim)
print("Shape of tensors: ", rank_4_tensor.shape)
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements: ", tf.size(rank_4_tensor))
print("Clean Total number of elements: ", tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensors:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements:  tf.Tensor(120, shape=(), dtype=int32)
Clean Total number of elements:  120


### Indexing tensors 
* Tensors can be indexed just like python lists

In [121]:
# Get the first 2 elements of each dimensions
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [123]:
# Get the first element from each dimensions from each index except for the final dimensions

rank_4_tensor[:1, :1, :1, :] #Note the shape for help

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [135]:
# Create a rank 2 tensor (2 Dimensions)

rank_2_tensor = tf.constant(np.arange(1,25, dtype=np.int32), shape = (6,4))
rank_2_tensor

<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])>

In [136]:
# Get the last item of each of our rank 2 tensor
rank_2_tensor[:, -1:]

<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
array([[ 4],
       [ 8],
       [12],
       [16],
       [20],
       [24]])>

In [148]:
# Add an extra dimensions to our rank 2 tensor
rank_3_tensor = rank_2_tensor[:,:,tf.newaxis] # or [..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(6, 4, 1), dtype=int32, numpy=
array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]],

       [[13],
        [14],
        [15],
        [16]],

       [[17],
        [18],
        [19],
        [20]],

       [[21],
        [22],
        [23],
        [24]]])>

In [ ]:
# Alternative Method ot expand dimensions
tf.expand_dims(rank_2_tensor, axis = -1) # -1 means expand the final axis

### Manipulating Tensors (Element Wise Tensor Operations)

**Basic Operations**
`+`, `-`, `*`, `/`

In [175]:
# Adding values to a tensor using the addition operations
tensor = tf.constant(np.arange(1,11), shape = [2,5])
tensor, tensor+10


(<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])>,
 <tf.Tensor: shape=(2, 5), dtype=int32, numpy=
 array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])>)

In [178]:
## Multiplication 
tensor*10


<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])>

In [176]:
# Subtraction
tensor-5

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[-4, -3, -2, -1,  0],
       [ 1,  2,  3,  4,  5]])>

In [177]:
# Using built-in tensor flow operations, usually faster

tf.math.multiply(tensor, 10) # Math optional

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])>

### Matrix Multiplication

**Rules**
* Number of Columns must match Number of rows
* Resulting matrix results in (#Rows of m1, #Cols of m2)
* (3,2) * (2,5) = (3,5)
    * Inner dimensions match

In [201]:
# Matrix multiplication in tensorflow

print(tensor)
tf.matmul(tensor, tf.transpose(tensor)), (tensor*tensor), tensor @ tf.transpose(tensor), tf.matmul(tensor, tf.reshape(tensor, shape=(5,2))), tf.reshape(tensor, shape = (5,2))


tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]], shape=(2, 5), dtype=int32)


(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 55, 130],
        [130, 330]])>,
 <tf.Tensor: shape=(2, 5), dtype=int32, numpy=
 array([[  1,   4,   9,  16,  25],
        [ 36,  49,  64,  81, 100]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 55, 130],
        [130, 330]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 95, 110],
        [220, 260]])>,
 <tf.Tensor: shape=(5, 2), dtype=int32, numpy=
 array([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])>)

### The Dot Product


In [197]:
# Perform the dot product on Tensor and its transpose

tf.tensordot(tensor, tf.transpose(tensor), axes = 0), tf.tensordot(tensor, tf.transpose(tensor), axes = 1), tf.tensordot(tensor, tf.transpose(tensor), axes = 2)

#Axis=0: Does not sum the products of the matrix multiplication. Each multiplied matrix is kept in a matrix
#Axis=1: Same as matrix multiplication. Sums the rows. 
#Axis=2: Sums the rows and columns. Returns a scalar

(<tf.Tensor: shape=(2, 5, 5, 2), dtype=int32, numpy=
 array([[[[  1,   6],
          [  2,   7],
          [  3,   8],
          [  4,   9],
          [  5,  10]],
 
         [[  2,  12],
          [  4,  14],
          [  6,  16],
          [  8,  18],
          [ 10,  20]],
 
         [[  3,  18],
          [  6,  21],
          [  9,  24],
          [ 12,  27],
          [ 15,  30]],
 
         [[  4,  24],
          [  8,  28],
          [ 12,  32],
          [ 16,  36],
          [ 20,  40]],
 
         [[  5,  30],
          [ 10,  35],
          [ 15,  40],
          [ 20,  45],
          [ 25,  50]]],
 
 
        [[[  6,  36],
          [ 12,  42],
          [ 18,  48],
          [ 24,  54],
          [ 30,  60]],
 
         [[  7,  42],
          [ 14,  49],
          [ 21,  56],
          [ 28,  63],
          [ 35,  70]],
 
         [[  8,  48],
          [ 16,  56],
          [ 24,  64],
          [ 32,  72],
          [ 40,  80]],
 
         [[  9,  54],
          [ 18,  6

### Changing the Datatype of a tensor


In [199]:
# Create a new tensor with default datatype (foat32)

B= tf.constant([1.7, 7.2])
B.dtype

tf.float32

In [202]:
# Change from float32 to float16. Precision reduction.

D = tf.cast(B, dtype = tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.2], dtype=float16)>,
 tf.float16)

### Aggregating tensors

* Aggregating tensors = condensing tensors from multiple values to smaller amount of values. 

In [208]:
# Get the absolute value
D = tf.constant([-7,-10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

Forms of aggregation:
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [261]:
# Creating a random tensor with values between 0 and 100 of size 50

E = tf.constant(np.random.randint(0,100, size = 50, dtype = np.int64))
E = tf.cast(E, tf.float32)
E, E.ndim, tf.size(E), E.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([55.,  1., 17., 62., 53., 72., 89., 61., 84., 19., 24., 30., 76.,
        49., 77., 16., 76., 56., 42., 95., 95., 65., 14.,  3., 91., 80.,
        17., 66., 75., 93., 59., 85., 87., 12., 33., 60., 78., 27., 36.,
        92., 60., 91., 66., 12., 36., 69., 97., 35., 41., 16.],
       dtype=float32)>,
 1,
 <tf.Tensor: shape=(), dtype=int32, numpy=50>,
 TensorShape([50]))

In [262]:
# Finding the minimum of a tensor
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [263]:
# Finding the maximum

tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=float32, numpy=97.0>

In [264]:
# Finding the sum 

tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=float32, numpy=2745.0>

In [265]:
#Finding the variance

import tensorflow_probability as tfp

E_mean = tf.reduce_mean(E)
e_vals = list()
for e in E:
    e_vals.append(e-E_mean)

E_var = tf.reduce_mean(tf.math.pow(e_vals,2))  # Have to make the tenor cast to a very big data type for the same accuracy as reduce_std. I created E originally as int64 and cast to float32 for maximum accuracy. 

E_var, tf.math.reduce_std(tf.cast(E,dtype = tf.float32))**2


(<tf.Tensor: shape=(), dtype=float32, numpy=815.89>,
 <tf.Tensor: shape=(), dtype=float32, numpy=815.8901>)

## Find the positional maximum and minimum.

In [270]:
# Create a new tensor for finding positional minimum and maximum

tf.random.set_seed(42)
F = tf.random.uniform(shape = [50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [274]:
# Find the positional maximum
tf.argmax(F)  #Finds the position of max
F[tf.argmax(F)], tf.reduce_max(F)


(<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>)

In [276]:
# Find positional minimum

F[tf.argmin(F)], tf.reduce_min(F)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

### Squeezing a tensor (removing all single dimensions)
* If there are any single dimensions, squeezing collapses them

In [289]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape = [50]), shape = (1,1,1,50,1))
G, G.shape

(<tf.Tensor: shape=(1, 1, 1, 50, 1), dtype=float32, numpy=
 array([[[[[0.6645621 ],
           [0.44100678],
           [0.3528825 ],
           [0.46448255],
           [0.03366041],
           [0.68467236],
           [0.74011743],
           [0.8724445 ],
           [0.22632635],
           [0.22319686],
           [0.3103881 ],
           [0.7223358 ],
           [0.13318717],
           [0.5480639 ],
           [0.5746088 ],
           [0.8996835 ],
           [0.00946367],
           [0.5212307 ],
           [0.6345445 ],
           [0.1993283 ],
           [0.72942245],
           [0.54583454],
           [0.10756552],
           [0.6767061 ],
           [0.6602763 ],
           [0.33695042],
           [0.60141766],
           [0.21062577],
           [0.8527372 ],
           [0.44062173],
           [0.9485276 ],
           [0.23752594],
           [0.81179297],
           [0.5263394 ],
           [0.494308  ],
           [0.21612847],
           [0.8457197 ],
           [0.87

In [288]:
G_sqeezed = tf.squeeze(G)
G_sqeezed, G_sqeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One-hot encoding
* A form of numerical encoding

In [300]:
# Create a list of indices

some_list = [0,1,2,3]  

# One hot encode for list
tf.one_hot(some_list, depth = 4)  #Must specify depth, number of variables

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [296]:
# Specify custom values for one hot encoding

tf.one_hot(some_list, depth=4, on_value ="True", off_value = "False")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'True', b'False', b'False', b'False'],
       [b'False', b'True', b'False', b'False'],
       [b'False', b'False', b'True', b'False'],
       [b'False', b'False', b'False', b'True']], dtype=object)>

### More complex operations
`power`, `sqrt`, `log`

In [304]:
# Squaring the tensor

H = tf.constant(np.arange(1,11), shape = [2,5])
tf.math.pow(H,2)

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]])>

In [312]:
# Square rooting tensor

tf.math.sqrt(tf.cast(H, tf.float32))  #Must cast to appropriate data type

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[1.       , 1.4142135, 1.7320508, 2.       , 2.236068 ],
       [2.4494898, 2.6457512, 2.828427 , 3.       , 3.1622777]],
      dtype=float32)>

### Tensors and NumPy
* Tensor flow interacts well with NumPy arrays

In [315]:
# Create a tensor directly from a NumPy array
J = tf.constant(np.array([3.,7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [316]:
# Convert our tensor back to a NumPy array

np.array(J), J.numpy

(array([ 3.,  7., 10.]),
 <bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>>)

In [318]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3.0, 7.0, 10.0]))  #Float64
tensor_J = tf.constant([3.0, 7.0, 10.0])           #Float32

numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)