# TensorFlow Concepts

In [1]:
# Import TensorFlow
import tensorflow as tf

print(tf.__version__)

2.12.0


In [2]:
# Create tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of Dimensions of a tensor (ndim stands for number of dimensions)

scalar.ndim

0

In [5]:
# Create a vector

vector = tf.constant([10,10])
vector

1

In [6]:
# Check the dimensions of vector

vector.ndim

1

In [8]:
# Create a Matrix

matrix = tf.constant([[10,7], [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [9]:
# Dimensions of a matrix
matrix.ndim

2

In [12]:
# Create a matrix with specified constant

specified_matrix = tf.constant([[10.,7],[7.,10], [3.0,13]], dtype = tf.float16, )
print(specified_matrix)
print(specified_matrix.ndim)

tf.Tensor(
[[10.  7.]
 [ 7. 10.]
 [ 3. 13.]], shape=(3, 2), dtype=float16)
2


In [14]:
# Create a Tensor, 3 dimensions

tensor = tf.constant([[[10,7],[7.,10]], [[3,13.],[13.,3]], [[14,4],[4,19]]])
tensor

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[10.,  7.],
        [ 7., 10.]],

       [[ 3., 13.],
        [13.,  3.]],

       [[14.,  4.],
        [ 4., 19.]]], dtype=float32)>

In [15]:
# Dimensions of tensor

tensor.ndim

3

What we've created so far:

* Scalar: A single number
* Vector: A number with a direction
* Matrix: A 2-dimensions array of numbers
* Tensor: an n-dimensions array of numbers (Where n is any number)